// ============================================================================
// Sabeel Class - 3D Character System (50 Cute 3D Cartoon Characters)
// Modular, expandable gamification library with Rarity & Mystery Box Gacha logic
// ============================================================================

export type CharacterRarity = 'common' | 'rare' | 'epic' | 'legendary';
export type CharacterCategory = 'quran' | 'science' | 'adventure' | 'leadership' | 'arts';

export interface Character3D {
  id: string;
  nameAr: string;
  titleAr: string;
  rarity: CharacterRarity;
  category: CharacterCategory;
  categoryAr: string;
  emoji: string;
  gender: 'boy' | 'girl' | 'neutral';
  descriptionAr: string;
  quoteAr: string;
  primaryColor: string;
  accentColor: string;
  bgGradient: string;
  stars: number;
}

export const RARITY_INFO: Record<
  CharacterRarity,
  {
    labelAr: string;
    stars: number;
    color: string;
    badgeBg: string;
    borderColor: string;
    glowClass: string;
    probabilityPercent: number;
    soundEffect: 'pop' | 'fanfare' | 'epic';
  }
> = {
  common: {
    labelAr: 'شائع',
    stars: 1,
    color: '#10b981', // emerald
    badgeBg: 'bg-emerald-500/15 text-emerald-700 dark:text-emerald-300 border-emerald-500/30',
    borderColor: 'border-emerald-400',
    glowClass: 'shadow-emerald-500/30 ring-emerald-400/50',
    probabilityPercent: 50,
    soundEffect: 'pop',
  },
  rare: {
    labelAr: 'نادر',
    stars: 2,
    color: '#0284c7', // sky/blue
    badgeBg: 'bg-sky-500/15 text-sky-700 dark:text-sky-300 border-sky-500/30',
    borderColor: 'border-sky-400',
    glowClass: 'shadow-sky-500/30 ring-sky-400/50',
    probabilityPercent: 30,
    soundEffect: 'pop',
  },
  epic: {
    labelAr: 'ملحمي',
    stars: 3,
    color: '#9333ea', // purple
    badgeBg: 'bg-purple-500/15 text-purple-700 dark:text-purple-300 border-purple-500/30',
    borderColor: 'border-purple-400',
    glowClass: 'shadow-purple-500/40 ring-purple-400/60',
    probabilityPercent: 15,
    soundEffect: 'fanfare',
  },
  legendary: {
    labelAr: 'أسطوري',
    stars: 4,
    color: '#f59e0b', // amber/gold
    badgeBg: 'bg-amber-500/20 text-amber-700 dark:text-amber-300 border-amber-500/40',
    borderColor: 'border-amber-400',
    glowClass: 'shadow-amber-500/50 ring-amber-400/80 animate-pulse',
    probabilityPercent: 5,
    soundEffect: 'epic',
  },
};

// ----------------------------------------------------------------------------
// 50 Handcrafted 3D Cute Cartoon Characters for Sabeel Class Students
// All child-friendly, inspiring, positive, respectful, and visually distinct.
// ----------------------------------------------------------------------------
export const CHARACTERS_3D_LIBRARY: Character3D[] = [
  // ==========================================
  // 🟢 COMMON CHARACTERS (20 Characters - 50% odds)
  // ==========================================
  {
    id: 'char_hafiz_junior',
    nameAr: 'الحافظ الصغير',
    titleAr: 'شبل الترتيل',
    rarity: 'common',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '📖',
    gender: 'boy',
    descriptionAr: 'طالب مجتهد يحفظ الآيات بصوت عذب ويرتدي طاقية بيضاء أنيقة.',
    quoteAr: 'ورتل القرآن ترتيلاً ✨',
    primaryColor: '#059669',
    accentColor: '#10b981',
    bgGradient: 'from-emerald-400 to-teal-600',
    stars: 1,
  },
  {
    id: 'char_hafiza_junior',
    nameAr: 'الحافظة الصغيرة',
    titleAr: 'زهرة القرآن',
    rarity: 'common',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '🌸',
    gender: 'girl',
    descriptionAr: 'فتاة نجيبة ومثابرة تضيء حلقة التحفيظ بابتسامتها وإتقانها.',
    quoteAr: 'القرآن ربيع قلبي 💖',
    primaryColor: '#ec4899',
    accentColor: '#f472b6',
    bgGradient: 'from-pink-400 to-rose-500',
    stars: 1,
  },
  {
    id: 'char_diligent_student_boy',
    nameAr: 'الطالب المجتهد',
    titleAr: 'صديق القلم',
    rarity: 'common',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '✏️',
    gender: 'boy',
    descriptionAr: 'لا يفوّت درساً، ودفتره منظم دائماً بخط عربي جميل.',
    quoteAr: 'العلم نور يُضاء به الدرب 💡',
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    bgGradient: 'from-sky-400 to-blue-600',
    stars: 1,
  },
  {
    id: 'char_diligent_student_girl',
    nameAr: 'الطالبة المتميزة',
    titleAr: 'نجمة الصف',
    rarity: 'common',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '📝',
    gender: 'girl',
    descriptionAr: 'تحرص على تحضير دروسها بدقة وتساعد زميلاتها في التسميع.',
    quoteAr: 'بالإصرار نصعد قمم النجاح 🌟',
    primaryColor: '#8b5cf6',
    accentColor: '#a78bfa',
    bgGradient: 'from-purple-400 to-indigo-500',
    stars: 1,
  },
  {
    id: 'char_little_reader',
    nameAr: 'القارئ اللبيب',
    titleAr: 'مستكشف الكتب',
    rarity: 'common',
    category: 'arts',
    categoryAr: 'الأدب والقراءة',
    emoji: '📚',
    gender: 'boy',
    descriptionAr: 'يحمل كتابه في كل مكان ويعشق قراءة قصص الأنبياء والصالحين.',
    quoteAr: 'خير جليس في الأنام كتاب 📗',
    primaryColor: '#0d9488',
    accentColor: '#2dd4bf',
    bgGradient: 'from-teal-400 to-emerald-600',
    stars: 1,
  },
  {
    id: 'char_sunshine_girl',
    nameAr: 'شمس الهدى',
    titleAr: 'ناشرة التفاؤل',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '☀️',
    gender: 'girl',
    descriptionAr: 'تبث البهجة والأخلاق الحسنة في قلوب كل من حولها في الحلقة.',
    quoteAr: 'الكلمة الطيبة صدقة 🌼',
    primaryColor: '#f59e0b',
    accentColor: '#fbbf24',
    bgGradient: 'from-amber-400 to-orange-500',
    stars: 1,
  },
  {
    id: 'char_little_artist',
    nameAr: 'الفنان الصغير',
    titleAr: 'رسام الإبداع',
    rarity: 'common',
    category: 'arts',
    categoryAr: 'الفنون والجمال',
    emoji: '🎨',
    gender: 'boy',
    descriptionAr: 'يزين لوحات الفصل بألوان زاهية وخطوط عربية بديعة.',
    quoteAr: 'إن الله جميل يحب الجمال 🎨',
    primaryColor: '#06b6d4',
    accentColor: '#22d3ee',
    bgGradient: 'from-cyan-400 to-teal-500',
    stars: 1,
  },
  {
    id: 'char_kind_helper',
    nameAr: 'الصديق الوفي',
    titleAr: 'عون الأصدقاء',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🤝',
    gender: 'boy',
    descriptionAr: 'مبادر دائماً لمساعدة أقرانه في ترتيب المصاحف ومراجعة الآيات.',
    quoteAr: 'خير الناس أنفعهم للناس 💙',
    primaryColor: '#3b82f6',
    accentColor: '#60a5fa',
    bgGradient: 'from-blue-400 to-sky-600',
    stars: 1,
  },
  {
    id: 'char_gardener_boy',
    nameAr: 'صديق الطبيعة',
    titleAr: 'غارس الأمل',
    rarity: 'common',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🌱',
    gender: 'boy',
    descriptionAr: 'يعتني بالنباتات ويتفكر في خلق الله البديع في الكون.',
    quoteAr: 'سبحان الخالق العظيم 🌿',
    primaryColor: '#16a34a',
    accentColor: '#4ade80',
    bgGradient: 'from-green-400 to-emerald-600',
    stars: 1,
  },
  {
    id: 'char_early_bird',
    nameAr: 'المبكر النشيط',
    titleAr: 'أول الحاضرين',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '⏰',
    gender: 'boy',
    descriptionAr: 'يصل إلى الحلقة قبل الجميع ويستفتح يومه بذكر الله.',
    quoteAr: 'بورك لأمتي في بكورها 🌅',
    primaryColor: '#d97706',
    accentColor: '#f59e0b',
    bgGradient: 'from-amber-400 to-yellow-600',
    stars: 1,
  },
  {
    id: 'char_little_reciter_girl',
    nameAr: 'المرتلة اللطيفة',
    titleAr: 'نغمة الإيمان',
    rarity: 'common',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '🕊️',
    gender: 'girl',
    descriptionAr: 'تتلو القرآن بخشوع وهدوء يبعث الطمأنينة في القلوب.',
    quoteAr: 'ألا بذكر الله تطمئن القلوب 🕊️',
    primaryColor: '#14b8a6',
    accentColor: '#2dd4bf',
    bgGradient: 'from-teal-400 to-cyan-600',
    stars: 1,
  },
  {
    id: 'char_smile_champion',
    nameAr: 'شبل الابتسامة',
    titleAr: 'صانع الفرح',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '😊',
    gender: 'boy',
    descriptionAr: 'ابتسامته لا تفارقه أبداً ويحب إسعاد زملائه وتشجيعهم.',
    quoteAr: 'تبسمك في وجه أخيك صدقة 😊',
    primaryColor: '#eab308',
    accentColor: '#facc15',
    bgGradient: 'from-yellow-400 to-amber-500',
    stars: 1,
  },
  {
    id: 'char_curious_thinker',
    nameAr: 'المفكر الفطن',
    titleAr: 'باحث الحكمة',
    rarity: 'common',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '🤔',
    gender: 'boy',
    descriptionAr: 'يطرح أسئلة ذكية عن معاني الآيات وأسرار لغة الضاد.',
    quoteAr: 'فاسألوا أهل الذكر إن كنتم لا تعلمون 🔍',
    primaryColor: '#6366f1',
    accentColor: '#818cf8',
    bgGradient: 'from-indigo-400 to-blue-600',
    stars: 1,
  },
  {
    id: 'char_polite_girl',
    nameAr: 'المهذبة الحكيمة',
    titleAr: 'أدب وسكينة',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🧕',
    gender: 'girl',
    descriptionAr: 'تتحلى بالأدب الرفيع وحسن الاستماع لمعلميها وأهلها.',
    quoteAr: 'أكمل المؤمنين إيماناً أحسنهم خلقاً 🌺',
    primaryColor: '#a855f7',
    accentColor: '#c084fc',
    bgGradient: 'from-purple-400 to-pink-500',
    stars: 1,
  },
  {
    id: 'char_little_navigator',
    nameAr: 'الملاح الصغير',
    titleAr: 'دليل السفر',
    rarity: 'common',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🧭',
    gender: 'boy',
    descriptionAr: 'يحب استكشاف الخرائط ومعرفة اتجاه القبلة في كل مكان يزوره.',
    quoteAr: 'وعلاماتٍ وبالنجمِ هم يهتدون 🧭',
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    bgGradient: 'from-sky-500 to-indigo-600',
    stars: 1,
  },
  {
    id: 'char_calligraphy_apprentice',
    nameAr: 'خطاط سبيل',
    titleAr: 'جمال الحرف',
    rarity: 'common',
    category: 'arts',
    categoryAr: 'الفنون والجمال',
    emoji: '✒️',
    gender: 'boy',
    descriptionAr: 'يتعلم خط النسخ والرقعة لكتابة الآيات القرآنية بأبهى حلة.',
    quoteAr: 'الخط الحسن يزيد الحق وضوحاً 📜',
    primaryColor: '#b45309',
    accentColor: '#d97706',
    bgGradient: 'from-amber-600 to-yellow-700',
    stars: 1,
  },
  {
    id: 'char_little_athlete',
    nameAr: 'النشيط القوي',
    titleAr: 'همة وعزيمة',
    rarity: 'common',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🏃',
    gender: 'boy',
    descriptionAr: 'يمارس الرياضة بانتظام ليحافظ على صحته وقوة بدنه في طاعة الله.',
    quoteAr: 'المؤمن القوي خير وأحب إلى الله ⚡',
    primaryColor: '#ef4444',
    accentColor: '#f87171',
    bgGradient: 'from-red-400 to-rose-600',
    stars: 1,
  },
  {
    id: 'char_peaceful_dove',
    nameAr: 'حمامة السلام',
    titleAr: 'روح الوداد',
    rarity: 'common',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🕊️',
    gender: 'girl',
    descriptionAr: 'تصلح بين الصديقات وتنشر المودة والكلمات الطيبة بين الجميع.',
    quoteAr: 'والصلح خير 🕊️',
    primaryColor: '#38bdf8',
    accentColor: '#7dd3fc',
    bgGradient: 'from-sky-300 to-blue-400',
    stars: 1,
  },
  {
    id: 'char_tajweed_learner',
    nameAr: 'طالب التجويد',
    titleAr: 'إتقان المخارج',
    rarity: 'common',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '🎯',
    gender: 'boy',
    descriptionAr: 'يركز على مخارج الحروف وأحكام النون والمدود بكل دقة.',
    quoteAr: 'حلية التلاوة زينة الأداء 🎙️',
    primaryColor: '#059669',
    accentColor: '#34d399',
    bgGradient: 'from-emerald-500 to-teal-700',
    stars: 1,
  },
  {
    id: 'char_cheerful_scout',
    nameAr: 'الكشاف المرح',
    titleAr: 'شجاعة ومساعدة',
    rarity: 'common',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🏕️',
    gender: 'boy',
    descriptionAr: 'يحب المغامرات في الهواء الطلق ومساعدة المخيمين وإطعام الطيور.',
    quoteAr: 'كن مستعداً لفعل الخير دائماً 🏕️',
    primaryColor: '#65a30d',
    accentColor: '#84cc16',
    bgGradient: 'from-lime-500 to-green-600',
    stars: 1,
  },

  // ==========================================
  // 🔵 RARE CHARACTERS (15 Characters - 30% odds)
  // ==========================================
  {
    id: 'char_young_knight',
    nameAr: 'الفارس الصغير',
    titleAr: 'عزم وشجاعة',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🛡️',
    gender: 'boy',
    descriptionAr: 'فارس نبيل يرتدي درعاً فضياً خفيفاً ويدافع عن الحق والعدل.',
    quoteAr: 'الشجاعة في نصرة الحق 🛡️',
    primaryColor: '#2563eb',
    accentColor: '#60a5fa',
    bgGradient: 'from-blue-500 to-indigo-700',
    stars: 2,
  },
  {
    id: 'char_little_princess',
    nameAr: 'أميرة النور',
    titleAr: 'تاج الوقار',
    rarity: 'rare',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '👑',
    gender: 'girl',
    descriptionAr: 'ترتدي تاجاً متلألئاً يرمز لتاج الوقار الذي تلبسه لوالديها بحفظ القرآن.',
    quoteAr: 'تاج الوقار شرف الدارين 👑',
    primaryColor: '#d946ef',
    accentColor: '#f0abfc',
    bgGradient: 'from-fuchsia-500 to-pink-600',
    stars: 2,
  },
  {
    id: 'char_young_scientist',
    nameAr: 'عالم المستقبل',
    titleAr: 'مستكشف الكون',
    rarity: 'rare',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '🔬',
    gender: 'boy',
    descriptionAr: 'يحمل مجهره ويكتشف عظمة الخالق في أدق المخلوقات والذرات.',
    quoteAr: 'سنريهم آياتنا في الآفاق 🔬',
    primaryColor: '#0891b2',
    accentColor: '#22d3ee',
    bgGradient: 'from-cyan-500 to-blue-600',
    stars: 2,
  },
  {
    id: 'char_little_inventor',
    nameAr: 'المخترع الذكي',
    titleAr: 'عبقري الأفكار',
    rarity: 'rare',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '💡',
    gender: 'boy',
    descriptionAr: 'يبتكر آلات روبوتية مسلية لمساعدة زملائه وتنظيم أوقات الحفظ.',
    quoteAr: 'الفكرة الذكية تبدأ بسؤال ⚙️',
    primaryColor: '#f97316',
    accentColor: '#fb923c',
    bgGradient: 'from-orange-500 to-amber-600',
    stars: 2,
  },
  {
    id: 'char_little_astronaut',
    nameAr: 'رائد الفضاء الصغير',
    titleAr: 'مستكشف الكواكب',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🚀',
    gender: 'boy',
    descriptionAr: 'يرتدي خوذة فضائية لطيفة ويسبح بين النجوم متأملاً صنع الله.',
    quoteAr: 'والسماء بنيناها بأيدٍ وإنا لموسعون 🌌',
    primaryColor: '#4f46e5',
    accentColor: '#818cf8',
    bgGradient: 'from-indigo-500 to-purple-700',
    stars: 2,
  },
  {
    id: 'char_oasis_guardian',
    nameAr: 'حارس الواحة',
    titleAr: 'حامي الخضرة',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🌴',
    gender: 'boy',
    descriptionAr: 'يحرس الواحة الغناء وينشر زراعة النخيل وظلال الخير في الصحراء.',
    quoteAr: 'إذا قامت الساعة وبيد أحدكم فسيلة فليغرسها 🌴',
    primaryColor: '#059669',
    accentColor: '#34d399',
    bgGradient: 'from-emerald-500 to-green-700',
    stars: 2,
  },
  {
    id: 'char_young_falconer',
    nameAr: 'الصقار الصغير',
    titleAr: 'عيون الصقر',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🦅',
    gender: 'boy',
    descriptionAr: 'يروض الصقر الوفي ويتعلم منه حدة البصر وسرعة الهمة والتحليق.',
    quoteAr: 'الهمة العالية لا ترضى إلا بالقمة 🦅',
    primaryColor: '#b45309',
    accentColor: '#f59e0b',
    bgGradient: 'from-amber-600 to-stone-700',
    stars: 2,
  },
  {
    id: 'char_star_sailor',
    nameAr: 'ملاح النجوم',
    titleAr: 'سيد الأمواج',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '⛵',
    gender: 'boy',
    descriptionAr: 'يقود سفينته الشراعية عبر البحار مستهدياً بالنجوم التي هداه الله بها.',
    quoteAr: 'وهو الذي سخر لكم البحر لتأكلوا منه لحماً طرياً 🌊',
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    bgGradient: 'from-sky-500 to-cyan-700',
    stars: 2,
  },
  {
    id: 'char_young_astronomer',
    nameAr: 'الفلكية الواعدة',
    titleAr: 'مراقبة الأقمار',
    rarity: 'rare',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '🔭',
    gender: 'girl',
    descriptionAr: 'ترصد هلال رمضان والأجرام السماوية بتلسكوبها الأنيق.',
    quoteAr: 'هو الذي جعل الشمس ضياءً والقمر نوراً 🌙',
    primaryColor: '#7c3aed',
    accentColor: '#a78bfa',
    bgGradient: 'from-violet-500 to-indigo-700',
    stars: 2,
  },
  {
    id: 'char_little_diplomat',
    nameAr: 'سفير الخير',
    titleAr: 'صوت الحكمة',
    rarity: 'rare',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🕊️',
    gender: 'boy',
    descriptionAr: 'يمثل دفعته بحكمة، فصيح اللسان وعذب المنطق في التعبير.',
    quoteAr: 'وقولوا للناس حسناً 💬',
    primaryColor: '#0f766e',
    accentColor: '#2dd4bf',
    bgGradient: 'from-teal-600 to-slate-800',
    stars: 2,
  },
  {
    id: 'char_young_architect',
    nameAr: 'مهندس المستقبل',
    titleAr: 'باني المنابر',
    rarity: 'rare',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '📐',
    gender: 'boy',
    descriptionAr: 'يصمم مجسمات للمساجد الأثرية والقباب والمنارات الإسلامية.',
    quoteAr: 'عمارة الأرض بإتقان وإيمان 🏛️',
    primaryColor: '#ea580c',
    accentColor: '#fb923c',
    bgGradient: 'from-orange-500 to-red-600',
    stars: 2,
  },
  {
    id: 'char_deep_diver',
    nameAr: 'غواص اللؤلؤ',
    titleAr: 'مكتشف الأعماق',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🤿',
    gender: 'boy',
    descriptionAr: 'يغوص في بحر القرآن ليستخرج درر المعاني ولآلئ الحكم.',
    quoteAr: 'يخرج منهما اللؤلؤ والمرجان 🐚',
    primaryColor: '#0369a1',
    accentColor: '#38bdf8',
    bgGradient: 'from-sky-600 to-blue-900',
    stars: 2,
  },
  {
    id: 'char_generous_heart',
    nameAr: 'ندى العطاء',
    titleAr: 'سحابة الجود',
    rarity: 'rare',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🎁',
    gender: 'girl',
    descriptionAr: 'تقتسم مكافآتها مع غيرها وتسعى دوماً لإدخال السرور على الجميع.',
    quoteAr: 'وما تنفقوا من خير فإن الله به عليم 💖',
    primaryColor: '#db2777',
    accentColor: '#f472b6',
    bgGradient: 'from-pink-500 to-rose-600',
    stars: 2,
  },
  {
    id: 'char_desert_wanderer',
    nameAr: 'رحالة البادية',
    titleAr: 'صبور الدروب',
    rarity: 'rare',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🐪',
    gender: 'boy',
    descriptionAr: 'يتعلم الصبر والقوة من حياة الصحراء ورمالها الذهبية.',
    quoteAr: 'أفلا ينظرون إلى الإبل كيف خلقت 🐪',
    primaryColor: '#d97706',
    accentColor: '#f59e0b',
    bgGradient: 'from-amber-500 to-yellow-700',
    stars: 2,
  },
  {
    id: 'char_speedy_memorizer',
    nameAr: 'سريع الحفظ',
    titleAr: 'برق الذاكرة',
    rarity: 'rare',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '⚡',
    gender: 'boy',
    descriptionAr: 'يحفظ الصفحة تلو الأخرى بسرعة فائقة وإتقان راسخ.',
    quoteAr: 'بل هو آياتٌ بيناتٌ في صدور الذين أوتوا العلم ⚡',
    primaryColor: '#e11d48',
    accentColor: '#fb7185',
    bgGradient: 'from-rose-500 to-red-600',
    stars: 2,
  },

  // ==========================================
  // 🟣 EPIC CHARACTERS (10 Characters - 15% odds)
  // ==========================================
  {
    id: 'char_mihrab_lion',
    nameAr: 'شبل المحراب',
    titleAr: 'فارس التهجد',
    rarity: 'epic',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '🦁',
    gender: 'boy',
    descriptionAr: 'بطل شجاع ذو صوت مهيب يقف في المحراب تالياً آيات ربه بخشوع.',
    quoteAr: 'أشبال اليوم فرسان الغد 🦁',
    primaryColor: '#7c3aed',
    accentColor: '#a78bfa',
    bgGradient: 'from-purple-600 via-indigo-600 to-blue-700',
    stars: 3,
  },
  {
    id: 'char_faith_flower',
    nameAr: 'زهرة الإيمان',
    titleAr: 'نور الطمأنينة',
    rarity: 'epic',
    category: 'quran',
    categoryAr: 'القرآن الكريم',
    emoji: '🌸',
    gender: 'girl',
    descriptionAr: 'تفيض خلقاً ونبلاً، وتحفظ الأجزاء القرآنية بتفوق باهر وملهم.',
    quoteAr: 'مثل المؤمن كالوردة يفوح شذاها في كل مكان 🌸',
    primaryColor: '#c026d3',
    accentColor: '#e879f9',
    bgGradient: 'from-fuchsia-600 via-pink-600 to-rose-700',
    stars: 3,
  },
  {
    id: 'char_sabeel_champion',
    nameAr: 'فارس سبيل',
    titleAr: 'سيد التحديات',
    rarity: 'epic',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '⚔️',
    gender: 'boy',
    descriptionAr: 'فارس أكاديمية سبيل المتوج بدروع العزم ووسام الصدارة الدائم.',
    quoteAr: 'سبيل العلم طريق إلى الجنة 🛡️',
    primaryColor: '#0284c7',
    accentColor: '#38bdf8',
    bgGradient: 'from-sky-500 via-blue-600 to-indigo-800',
    stars: 3,
  },
  {
    id: 'char_wisdom_sage',
    nameAr: 'حكيم الزمان',
    titleAr: 'جامع الحكمة',
    rarity: 'epic',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '📜',
    gender: 'boy',
    descriptionAr: 'يحمل مخطوطات قديمة ويفسر معاني القرآن بحكمة بالغة ووقار.',
    quoteAr: 'ومن يؤتَ الحكمة فقد أوتي خيراً كثيراً 📜',
    primaryColor: '#4338ca',
    accentColor: '#818cf8',
    bgGradient: 'from-indigo-600 via-purple-700 to-slate-900',
    stars: 3,
  },
  {
    id: 'char_galaxy_explorer',
    nameAr: 'مكتشف المجرات',
    titleAr: 'سيد الأفق',
    rarity: 'epic',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '🌌',
    gender: 'boy',
    descriptionAr: 'يطوف في عوالم المعرفة والعلوم الكونية باحثاً عن عظمة الصانع.',
    quoteAr: 'فلا أقسم بمواقع النجوم وإنه لقسم لو تعلمون عظيم 🌌',
    primaryColor: '#6d28d9',
    accentColor: '#a78bfa',
    bgGradient: 'from-violet-600 via-purple-800 to-indigo-950',
    stars: 3,
  },
  {
    id: 'char_brave_archer',
    nameAr: 'رامي العزم',
    titleAr: 'دقيق الهدف',
    rarity: 'epic',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '🏹',
    gender: 'boy',
    descriptionAr: 'قوسه يرمز لتركيزه الفائق في إصابة أهداف الحفظ والمراجعة.',
    quoteAr: 'الرمي ثبات والهدف قمة 🎯',
    primaryColor: '#059669',
    accentColor: '#34d399',
    bgGradient: 'from-emerald-600 via-teal-700 to-slate-900',
    stars: 3,
  },
  {
    id: 'char_golden_pen',
    nameAr: 'سفير القلم',
    titleAr: 'كاتب الوحي',
    rarity: 'epic',
    category: 'arts',
    categoryAr: 'الفنون والجمال',
    emoji: '🖋️',
    gender: 'boy',
    descriptionAr: 'قلمه مذهب يكتب به المصحف الشريف بحروف ناطقة بالجمال والروعة.',
    quoteAr: 'ن والقلم وما يسطرون ✒️',
    primaryColor: '#b45309',
    accentColor: '#f59e0b',
    bgGradient: 'from-amber-600 via-yellow-600 to-stone-900',
    stars: 3,
  },
  {
    id: 'char_nature_guardian',
    nameAr: 'حارسة الفردوس',
    titleAr: 'قلب النقاء',
    rarity: 'epic',
    category: 'leadership',
    categoryAr: 'الأخلاق والقيادة',
    emoji: '🦚',
    gender: 'girl',
    descriptionAr: 'ترتدي أثواباً مطرزة كألوان الطاووس وتنشر الخير في كل ركن.',
    quoteAr: 'إن الذين آمنوا وعملوا الصالحات كانت لهم جنات الفردوس نزلاً 🦚',
    primaryColor: '#0d9488',
    accentColor: '#2dd4bf',
    bgGradient: 'from-teal-500 via-emerald-600 to-cyan-800',
    stars: 3,
  },
  {
    id: 'char_lightning_master',
    nameAr: 'سيد البرهان',
    titleAr: 'صاعقة الحجة',
    rarity: 'epic',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '⚡',
    gender: 'boy',
    descriptionAr: 'حجته قاطعة، ذكي الفؤاد، وسريع البديهة في استحضار الشواهد.',
    quoteAr: 'قل هاتوا برهانكم إن كنتم صادقين ⚡',
    primaryColor: '#e11d48',
    accentColor: '#f43f5e',
    bgGradient: 'from-rose-600 via-red-700 to-indigo-900',
    stars: 3,
  },
  {
    id: 'char_time_traveler',
    nameAr: 'رحالة العصور',
    titleAr: 'مستلهم السير',
    rarity: 'epic',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '⏳',
    gender: 'boy',
    descriptionAr: 'يعيش في قصص التاريخ الإسلامي ويستلهم همم الصحابة والعلماء.',
    quoteAr: 'لقد كان في قصصهم عبرة لأولي الألباب ⏳',
    primaryColor: '#d97706',
    accentColor: '#fbbf24',
    bgGradient: 'from-amber-600 via-orange-700 to-purple-900',
    stars: 3,
  },

  // ==========================================
  // 🟡 LEGENDARY CHARACTERS (5 Characters - 5% odds)
  // Ultimate Prestigious Characters for Sabeel Class
  // ==========================================
  {
    id: 'char_khalid_sword',
    nameAr: 'سيف العزيمة',
    titleAr: 'الفارس الذي لا يُقهر',
    rarity: 'legendary',
    category: 'leadership',
    categoryAr: 'القيادة والبطولة',
    emoji: '🗡️',
    gender: 'boy',
    descriptionAr: 'أسطورة الصمود؛ يحمل درع النصر وتاج الإقدام، لا يتراجع في طلب المعالي.',
    quoteAr: 'من سار على الدرب وصل، ومن طلب العلا سهر الليالي 🌟',
    primaryColor: '#d97706',
    accentColor: '#fbbf24',
    bgGradient: 'from-amber-500 via-yellow-400 to-amber-700',
    stars: 4,
  },
  {
    id: 'char_salahuddin_eagle',
    nameAr: 'نسر القدس',
    titleAr: 'رمز العدالة والوفاء',
    rarity: 'legendary',
    category: 'leadership',
    categoryAr: 'القيادة والبطولة',
    emoji: '🦅',
    gender: 'boy',
    descriptionAr: 'قائد نبيل يرتدي عباءة الفخار، يجمع بين الرحمة والحزم والشرف الرفيع.',
    quoteAr: 'العدل أساس الملك وحلية القادة العظام 👑',
    primaryColor: '#059669',
    accentColor: '#34d399',
    bgGradient: 'from-emerald-500 via-teal-400 to-amber-600',
    stars: 4,
  },
  {
    id: 'char_asmaa_courage',
    nameAr: 'ذات النطاقين',
    titleAr: 'سيدة الشجاعة والتضحية',
    rarity: 'legendary',
    category: 'leadership',
    categoryAr: 'القيادة والبطولة',
    emoji: '⭐',
    gender: 'girl',
    descriptionAr: 'قدوة في التضحية والشجاعة، تحمل مشعل النور واليقين وتلهم أجيالاً.',
    quoteAr: 'إن مع العسر يسراً، واليقين طريق الظفر 💖',
    primaryColor: '#ec4899',
    accentColor: '#f472b6',
    bgGradient: 'from-pink-500 via-rose-400 to-amber-500',
    stars: 4,
  },
  {
    id: 'char_celestial_scholar',
    nameAr: 'عالم الأكوان الأسطوري',
    titleAr: 'نور البصيرة والضياء',
    rarity: 'legendary',
    category: 'science',
    categoryAr: 'العلم والمعرفة',
    emoji: '🔮',
    gender: 'boy',
    descriptionAr: 'تتوهج حوله هالة سماوية من النجوم وحروف القرآن المضيئة بالإتقان.',
    quoteAr: 'يرفع الله الذين آمنوا منكم والذين أوتوا العلم درجات 🌠',
    primaryColor: '#8b5cf6',
    accentColor: '#c084fc',
    bgGradient: 'from-violet-600 via-amber-400 to-indigo-800',
    stars: 4,
  },
  {
    id: 'char_sabeel_phoenix',
    nameAr: 'طائر العزم الذهبي',
    titleAr: 'سيد الصدارة المطلق',
    rarity: 'legendary',
    category: 'adventure',
    categoryAr: 'المغامرة والاستكشاف',
    emoji: '✨',
    gender: 'neutral',
    descriptionAr: 'الرمز الذهبي الأسمى لأكاديمية سبيل؛ يجسد كل قيم التفوق والهمة والمحبة.',
    quoteAr: 'وفوق كل ذي علم عليم ✨ سبيلنا نحو الخلود 👑',
    primaryColor: '#f59e0b',
    accentColor: '#fde047',
    bgGradient: 'from-amber-400 via-yellow-300 to-orange-600',
    stars: 4,
  },
];

// ----------------------------------------------------------------------------
// Public API Functions for Character System
// ----------------------------------------------------------------------------

export function getAllCharacters(): Character3D[] {
  return CHARACTERS_3D_LIBRARY;
}

export function getCharacterById(id?: string): Character3D {
  if (!id) return CHARACTERS_3D_LIBRARY[0];
  const found = CHARACTERS_3D_LIBRARY.find((c) => c.id === id);
  return found || CHARACTERS_3D_LIBRARY[0];
}

export function getCharactersByRarity(rarity: CharacterRarity): Character3D[] {
  return CHARACTERS_3D_LIBRARY.filter((c) => c.rarity === rarity);
}

export function getCharactersByCategory(category: CharacterCategory): Character3D[] {
  return CHARACTERS_3D_LIBRARY.filter((c) => c.category === category);
}

/**
 * Roll a random character based on game gacha odds:
 * Common: 50%
 * Rare: 30%
 * Epic: 15%
 * Legendary: 5%
 */
export function rollRandomCharacter(customWeights?: Record<CharacterRarity, number>): Character3D {
  const weights = customWeights || {
    common: 50,
    rare: 30,
    epic: 15,
    legendary: 5,
  };

  const rand = Math.random() * 100;
  let targetRarity: CharacterRarity = 'common';

  if (rand < weights.legendary) {
    targetRarity = 'legendary';
  } else if (rand < weights.legendary + weights.epic) {
    targetRarity = 'epic';
  } else if (rand < weights.legendary + weights.epic + weights.rare) {
    targetRarity = 'rare';
  } else {
    targetRarity = 'common';
  }

  const pool = getCharactersByRarity(targetRarity);
  const randomIndex = Math.floor(Math.random() * pool.length);
  return pool[randomIndex];
}
