export interface IslamicAvatarDef {
  id: string;
  name: string;
  title: string;
  category: string;
  characterTag: string;
  icon: string;
  fallbackColor: string;
  badge: string;
  gender: 'male' | 'female' | 'any';
  label: string;
  emoji: string;
  animeSeries?: string; // alias for backwards compatibility
  gifUrl?: string;
}

export const ISLAMIC_CATEGORIES = [
  'الكل',
  'الصحابة الكرام',
  'الصحابيات الجليلات',
  'القادة والفاتحون',
  'علماء الحضارة',
  'أئمة وقراء',
  'أشبال وزهرات القرآن'
] as const;

export const ISLAMIC_AVATARS: IslamicAvatarDef[] = [
  // --- 1. الصحابة الكرام (1-25) ---
  {
    id: 'islamic_1',
    name: 'أبو بكر الصديق',
    title: 'أول الخلفاء الراشدين ورفيق الغار',
    category: 'الصحابة الكرام',
    characterTag: 'الصديق 🌟',
    icon: '🌟',
    fallbackColor: 'from-amber-600 via-amber-500 to-yellow-500',
    badge: 'الرفيق الصادق',
    gender: 'male',
    label: 'أبو بكر الصديق',
    emoji: '🌟'
  },
  {
    id: 'islamic_2',
    name: 'عمر بن الخطاب',
    title: 'الفاروق وأمير المؤمنين',
    category: 'الصحابة الكرام',
    characterTag: 'الفاروق ⚖️',
    icon: '⚖️',
    fallbackColor: 'from-emerald-700 via-teal-700 to-emerald-900',
    badge: 'إمام العدل',
    gender: 'male',
    label: 'عمر بن الخطاب',
    emoji: '⚖️'
  },
  {
    id: 'islamic_3',
    name: 'عثمان بن عفان',
    title: 'ذو النورين وجامع القرآن',
    category: 'الصحابة الكرام',
    characterTag: 'ذو النورين 📖',
    icon: '📖',
    fallbackColor: 'from-sky-700 via-blue-600 to-indigo-800',
    badge: 'جامع المصحف',
    gender: 'male',
    label: 'عثمان بن عفان',
    emoji: '📖'
  },
  {
    id: 'islamic_4',
    name: 'علي بن أبي طالب',
    title: 'أمير المؤمنين وباب مدينة العلم',
    category: 'الصحابة الكرام',
    characterTag: 'أسد خيبر 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-teal-600 via-emerald-600 to-cyan-700',
    badge: 'فارس الشجاعة',
    gender: 'male',
    label: 'علي بن أبي طالب',
    emoji: '🛡️'
  },
  {
    id: 'islamic_5',
    name: 'خالد بن الوليد',
    title: 'سيف الله المسلول وقاهر الروم والفرس',
    category: 'الصحابة الكرام',
    characterTag: 'سيف الله ⚔️',
    icon: '⚔️',
    fallbackColor: 'from-amber-700 via-orange-600 to-red-800',
    badge: 'الفارس الذي لا يُهزم',
    gender: 'male',
    label: 'خالد بن الوليد',
    emoji: '⚔️'
  },
  {
    id: 'islamic_6',
    name: 'سعد بن أبي وقاص',
    title: 'فارس القادسية وأول من رمى بسهم في الإسلام',
    category: 'الصحابة الكرام',
    characterTag: 'رامي السهام 🏹',
    icon: '🏹',
    fallbackColor: 'from-indigo-700 via-purple-700 to-slate-800',
    badge: 'فارس القادسية',
    gender: 'male',
    label: 'سعد بن أبي وقاص',
    emoji: '🏹'
  },
  {
    id: 'islamic_7',
    name: 'حمزة بن عبد المطلب',
    title: 'أسد الله وأسد رسوله وسيد الشهداء',
    category: 'الصحابة الكرام',
    characterTag: 'أسد الله 🦁',
    icon: '🦁',
    fallbackColor: 'from-red-700 via-amber-700 to-orange-900',
    badge: 'سيد الشهداء',
    gender: 'male',
    label: 'حمزة بن عبد المطلب',
    emoji: '🦁'
  },
  {
    id: 'islamic_8',
    name: 'مصعب بن عمير',
    title: 'أول سفير في الإسلام ومقرئ يثرب',
    category: 'الصحابة الكرام',
    characterTag: 'سفير الإسلام 📜',
    icon: '📜',
    fallbackColor: 'from-emerald-600 via-teal-600 to-slate-800',
    badge: 'سفير الهدى',
    gender: 'male',
    label: 'مصعب بن عمير',
    emoji: '📜'
  },
  {
    id: 'islamic_9',
    name: 'أبو عبيدة بن الجراح',
    title: 'أمين هذه الأمة وفاتح الشام',
    category: 'الصحابة الكرام',
    characterTag: 'أمين الأمة 💎',
    icon: '💎',
    fallbackColor: 'from-cyan-700 via-blue-700 to-slate-900',
    badge: 'أمين الأمة',
    gender: 'male',
    label: 'أبو عبيدة بن الجراح',
    emoji: '💎'
  },
  {
    id: 'islamic_10',
    name: 'الزبير بن العوام',
    title: 'حواري رسول الله وفارس اليرموك',
    category: 'الصحابة الكرام',
    characterTag: 'حواري الرسول 🗡️',
    icon: '🗡️',
    fallbackColor: 'from-violet-700 via-indigo-700 to-purple-900',
    badge: 'حواري النبي',
    gender: 'male',
    label: 'الزبير بن العوام',
    emoji: '🗡️'
  },
  {
    id: 'islamic_11',
    name: 'طلحة بن عبيد الله',
    title: 'صقر أحد وطلحة الخير والجود',
    category: 'الصحابة الكرام',
    characterTag: 'صقر أحد 🦅',
    icon: '🦅',
    fallbackColor: 'from-amber-600 via-orange-700 to-stone-800',
    badge: 'الشهيد الحي',
    gender: 'male',
    label: 'طلحة بن عبيد الله',
    emoji: '🦅'
  },
  {
    id: 'islamic_12',
    name: 'سلمان الفارسي',
    title: 'الباحث عن الحقيقة وصاحب فكرة الخندق',
    category: 'الصحابة الكرام',
    characterTag: 'مهندس الخندق 🏰',
    icon: '🏰',
    fallbackColor: 'from-emerald-700 via-green-700 to-teal-900',
    badge: 'منا آل البيت',
    gender: 'male',
    label: 'سلمان الفارسي',
    emoji: '🏰'
  },
  {
    id: 'islamic_13',
    name: 'بلال بن رباح',
    title: 'مؤذن الرسول وصاحب أحدٌ أحد',
    category: 'الصحابة الكرام',
    characterTag: 'صوت التوحيد 🕌',
    icon: '🕌',
    fallbackColor: 'from-sky-600 via-blue-700 to-slate-900',
    badge: 'مؤذن الرسول',
    gender: 'male',
    label: 'بلال بن رباح',
    emoji: '🕌'
  },
  {
    id: 'islamic_14',
    name: 'عبد الله بن مسعود',
    title: 'صاحب النعلين وسادس من أسلم وإمام التلاوة',
    category: 'الصحابة الكرام',
    characterTag: 'إمام التلاوة 🎙️',
    icon: '🎙️',
    fallbackColor: 'from-teal-600 via-emerald-700 to-cyan-900',
    badge: 'حامل المصحف',
    gender: 'male',
    label: 'عبد الله بن مسعود',
    emoji: '🎙️'
  },
  {
    id: 'islamic_15',
    name: 'معاذ بن جبل',
    title: 'أعلم الأمة بالحلال والحرام وإمام العلماء',
    category: 'الصحابة الكرام',
    characterTag: 'عالم الحلال والحرام 🎓',
    icon: '🎓',
    fallbackColor: 'from-indigo-600 via-blue-700 to-slate-800',
    badge: 'إمام الفقهاء',
    gender: 'male',
    label: 'معاذ بن جبل',
    emoji: '🎓'
  },
  {
    id: 'islamic_16',
    name: 'أسامة بن زيد',
    title: 'الحِب بن الحِب وأصغر قائد جيش في الإسلام',
    category: 'الصحابة الكرام',
    characterTag: 'القائد الشاب 🚩',
    icon: '🚩',
    fallbackColor: 'from-rose-600 via-amber-600 to-slate-900',
    badge: 'راية النصر',
    gender: 'male',
    label: 'أسامة بن زيد',
    emoji: '🚩'
  },
  {
    id: 'islamic_17',
    name: 'زيد بن ثابت',
    title: 'كاتب الوحي وشيخ المقرئين والفرائض',
    category: 'الصحابة الكرام',
    characterTag: 'كاتب الوحي ✍️',
    icon: '✍️',
    fallbackColor: 'from-amber-600 via-yellow-600 to-stone-800',
    badge: 'جامع السطور',
    gender: 'male',
    label: 'زيد بن ثابت',
    emoji: '✍️'
  },
  {
    id: 'islamic_18',
    name: 'عمار بن ياسر',
    title: 'من السابقين وأولياء الله الصابرين',
    category: 'الصحابة الكرام',
    characterTag: 'رمز الثبات ⚡',
    icon: '⚡',
    fallbackColor: 'from-slate-700 via-stone-700 to-amber-900',
    badge: 'الثابت على الحق',
    gender: 'male',
    label: 'عمار بن ياسر',
    emoji: '⚡'
  },
  {
    id: 'islamic_19',
    name: 'البراء بن مالك',
    title: 'الفارس المغوار مستجاب الدعوة وبطل اليمامة',
    category: 'الصحابة الكرام',
    characterTag: 'فارس اليمامة 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-red-600 via-orange-600 to-slate-900',
    badge: 'مستجاب الدعاء',
    gender: 'male',
    label: 'البراء بن مالك',
    emoji: '🛡️'
  },
  {
    id: 'islamic_20',
    name: 'جعفر بن أبي طالب',
    title: 'جعفر الطيار وذو الجناحين وبطل مؤتة',
    category: 'الصحابة الكرام',
    characterTag: 'الطيار 🕊️',
    icon: '🕊️',
    fallbackColor: 'from-sky-600 via-cyan-600 to-blue-900',
    badge: 'ذو الجناحين',
    gender: 'male',
    label: 'جعفر بن أبي طالب',
    emoji: '🕊️'
  },
  {
    id: 'islamic_21',
    name: 'عبد الرحمن بن عوف',
    title: 'التاجر الصدوق والجواد المبشر بالجنة',
    category: 'الصحابة الكرام',
    characterTag: 'التاجر الصدوق 💰',
    icon: '💰',
    fallbackColor: 'from-amber-500 via-yellow-600 to-emerald-800',
    badge: 'المنفق في سبيل الله',
    gender: 'male',
    label: 'عبد الرحمن بن عوف',
    emoji: '💰'
  },
  {
    id: 'islamic_22',
    name: 'سعيد بن زيد',
    title: 'أحد العشرة المبشرين ورائد الفتح',
    category: 'الصحابة الكرام',
    characterTag: 'المبشر بالجنة 🌿',
    icon: '🌿',
    fallbackColor: 'from-emerald-600 via-teal-700 to-slate-800',
    badge: 'فارس اليرموك',
    gender: 'male',
    label: 'سعيد بن زيد',
    emoji: '🌿'
  },
  {
    id: 'islamic_23',
    name: 'عبد الله بن عباس',
    title: 'حبر الأمة وترجمان القرآن الكريم',
    category: 'الصحابة الكرام',
    characterTag: 'ترجمان القرآن 📚',
    icon: '📚',
    fallbackColor: 'from-blue-700 via-indigo-700 to-sky-900',
    badge: 'حبر الأمة',
    gender: 'male',
    label: 'عبد الله بن عباس',
    emoji: '📚'
  },
  {
    id: 'islamic_24',
    name: 'عبد الله بن عمر',
    title: 'العابد الزاهد والحريص على السنة',
    category: 'الصحابة الكرام',
    characterTag: 'متبع السنة 🕯️',
    icon: '🕯️',
    fallbackColor: 'from-teal-700 via-cyan-700 to-slate-900',
    badge: 'حارس الأثر',
    gender: 'male',
    label: 'عبد الله بن عمر',
    emoji: '🕯️'
  },
  {
    id: 'islamic_25',
    name: 'صهيب الرومي',
    title: 'الرابح في البيع لله والمهاجر الصادق',
    category: 'الصحابة الكرام',
    characterTag: 'ربح البيع 💎',
    icon: '💎',
    fallbackColor: 'from-amber-600 via-rose-600 to-stone-900',
    badge: 'ربح البيع يا صهيب',
    gender: 'male',
    label: 'صهيب الرومي',
    emoji: '💎'
  },

  // --- 2. الصحابيات الجليلات وأمهات المؤمنين (26-40) ---
  {
    id: 'islamic_26',
    name: 'خديجة بنت خويلد',
    title: 'أم المؤمنين وسيدة نساء قريش وأول من آمن',
    category: 'الصحابيات الجليلات',
    characterTag: 'الطاهرة 🌸',
    icon: '🌸',
    fallbackColor: 'from-rose-600 via-pink-600 to-purple-800',
    badge: 'أول المؤمنات',
    gender: 'female',
    label: 'خديجة بنت خويلد',
    emoji: '🌸'
  },
  {
    id: 'islamic_27',
    name: 'عائشة بنت أبي بكر',
    title: 'الصديقة بنت الصديق وفقيهة الأمة ومعلمة الأجيال',
    category: 'الصحابيات الجليلات',
    characterTag: 'فقيهة الأمة 📖',
    icon: '📖',
    fallbackColor: 'from-pink-600 via-rose-500 to-amber-700',
    badge: 'حبيبة المصطفى',
    gender: 'female',
    label: 'عائشة بنت أبي بكر',
    emoji: '📖'
  },
  {
    id: 'islamic_28',
    name: 'فاطمة الزهراء',
    title: 'سيدة نساء العالمين وبضعة الرسول ﷺ',
    category: 'الصحابيات الجليلات',
    characterTag: 'الزهراء 🌷',
    icon: '🌷',
    fallbackColor: 'from-teal-600 via-emerald-600 to-rose-800',
    badge: 'سيدة نساء الجنة',
    gender: 'female',
    label: 'فاطمة الزهراء',
    emoji: '🌷'
  },
  {
    id: 'islamic_29',
    name: 'أسماء بنت أبي بكر',
    title: 'ذات النطاقين وبطلة الهجرة النبوية',
    category: 'الصحابيات الجليلات',
    characterTag: 'ذات النطاقين 🎗️',
    icon: '🎗️',
    fallbackColor: 'from-amber-600 via-rose-600 to-purple-900',
    badge: 'بطلة الهجرة',
    gender: 'female',
    label: 'أسماء بنت أبي بكر',
    emoji: '🎗️'
  },
  {
    id: 'islamic_30',
    name: 'سمية بنت خياط',
    title: 'أول شهيدة في الإسلام ورمز التضحية',
    category: 'الصحابيات الجليلات',
    characterTag: 'أول شهيدة 🕊️',
    icon: '🕊️',
    fallbackColor: 'from-rose-700 via-red-700 to-slate-900',
    badge: 'رمز التضحية',
    gender: 'female',
    label: 'سمية بنت خياط',
    emoji: '🕊️'
  },
  {
    id: 'islamic_31',
    name: 'نسيبة بنت كعب',
    title: 'أم عمارة بطلة يوم أحد والمدافعة عن الرسول',
    category: 'الصحابيات الجليلات',
    characterTag: 'أم عمارة 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-purple-700 via-rose-700 to-slate-900',
    badge: 'بطلة يوم أحد',
    gender: 'female',
    label: 'نسيبة بنت كعب',
    emoji: '🛡️'
  },
  {
    id: 'islamic_32',
    name: 'أم سليم بنت ملحان',
    title: 'الرميصاء صاحبة أعظم مهر وأم أنس بن مالك',
    category: 'الصحابيات الجليلات',
    characterTag: 'الرميصاء 🌺',
    icon: '🌺',
    fallbackColor: 'from-emerald-600 via-teal-700 to-rose-700',
    badge: 'سيدة الحكمة',
    gender: 'female',
    label: 'أم سليم بنت ملحان',
    emoji: '🌺'
  },
  {
    id: 'islamic_33',
    name: 'الخنساء تماضر بنت عمرو',
    title: 'شاعرة الصبر والجهاد وأم الشهداء الأربعة',
    category: 'الصحابيات الجليلات',
    characterTag: 'أم الشهداء 📜',
    icon: '📜',
    fallbackColor: 'from-amber-700 via-stone-700 to-slate-900',
    badge: 'شاعرة الصبر',
    gender: 'female',
    label: 'الخنساء تماضر بنت عمرو',
    emoji: '📜'
  },
  {
    id: 'islamic_34',
    name: 'حفصة بنت عمر',
    title: 'أم المؤمنين وحارسة المصحف الشريف الأول',
    category: 'الصحابيات الجليلات',
    characterTag: 'حارسة المصحف 📖',
    icon: '📖',
    fallbackColor: 'from-indigo-600 via-purple-700 to-slate-900',
    badge: 'صوامة قوامة',
    gender: 'female',
    label: 'حفصة بنت عمر',
    emoji: '📖'
  },
  {
    id: 'islamic_35',
    name: 'زينب بنت علي بن أبي طالب',
    title: 'عقيلة بني هاشم وفصيحة آل البيت وصابرة كربلاء',
    category: 'الصحابيات الجليلات',
    characterTag: 'عقيلة الهاشميين 🌟',
    icon: '🌟',
    fallbackColor: 'from-teal-700 via-emerald-800 to-slate-900',
    badge: 'بطلة الصبر والبيان',
    gender: 'female',
    label: 'زينب بنت علي',
    emoji: '🌟'
  },
  {
    id: 'islamic_36',
    name: 'أم سلمة هند بنت أبي أمية',
    title: 'أم المؤمنين صاحبة الرأي السديد يوم الحديبية',
    category: 'الصحابيات الجليلات',
    characterTag: 'صاحبة الرأي السديد 💡',
    icon: '💡',
    fallbackColor: 'from-sky-700 via-indigo-700 to-purple-900',
    badge: 'سداد الرأي',
    gender: 'female',
    label: 'أم سلمة هند',
    emoji: '💡'
  },
  {
    id: 'islamic_37',
    name: 'رفيدة الأسلمية',
    title: 'أول ممرضة وطبيبة جراحة في تاريخ الإسلام',
    category: 'الصحابيات الجليلات',
    characterTag: 'أول طبيبة 🩺',
    icon: '🩺',
    fallbackColor: 'from-cyan-600 via-teal-700 to-slate-800',
    badge: 'رائدة الطب النبوي',
    gender: 'female',
    label: 'رفيدة الأسلمية',
    emoji: '🩺'
  },
  {
    id: 'islamic_38',
    name: 'الشفاء بنت عبد الله',
    title: 'المعلمة الأولى وقاضية الحسبة والأسواق في عهد عمر',
    category: 'الصحابيات الجليلات',
    characterTag: 'معلمة القراءة 📚',
    icon: '📚',
    fallbackColor: 'from-emerald-700 via-green-800 to-slate-900',
    badge: 'أمينة الحسبة',
    gender: 'female',
    label: 'الشفاء بنت عبد الله',
    emoji: '📚'
  },
  {
    id: 'islamic_39',
    name: 'مريم بنت عمران',
    title: 'سيدة الصديقات وسيدة نساء أهل الجنة',
    category: 'الصحابيات الجليلات',
    characterTag: 'الصديقة البتول 🕊️',
    icon: '🕊️',
    fallbackColor: 'from-sky-600 via-blue-600 to-indigo-800',
    badge: 'مثل الطهر والعبادة',
    gender: 'female',
    label: 'مريم بنت عمران',
    emoji: '🕊️'
  },
  {
    id: 'islamic_40',
    name: 'آسية بنت مزاحم',
    title: 'امرأة فرعون ورمز الصمود الإيماني العظيم',
    category: 'الصحابيات الجليلات',
    characterTag: 'رمز الثبات 👑',
    icon: '👑',
    fallbackColor: 'from-amber-600 via-rose-700 to-slate-900',
    badge: 'بنت بيتاً في الجنة',
    gender: 'female',
    label: 'آسية بنت مزاحم',
    emoji: '👑'
  },

  // --- 3. القادة والفاتحون (41-60) ---
  {
    id: 'islamic_41',
    name: 'صلاح الدين الأيوبي',
    title: 'محرر بيت المقدس وبطل معركة حطين',
    category: 'القادة والفاتحون',
    characterTag: 'محرر القدس 🕌',
    icon: '🕌',
    fallbackColor: 'from-amber-600 via-yellow-600 to-emerald-900',
    badge: 'الناصر لدين الله',
    gender: 'male',
    label: 'صلاح الدين الأيوبي',
    emoji: '🕌'
  },
  {
    id: 'islamic_42',
    name: 'طارق بن زياد',
    title: 'فاتح الأندلس وصاحب العزيمة التي شقت المضيق',
    category: 'القادة والفاتحون',
    characterTag: 'فاتح الأندلس ⚔️',
    icon: '⚔️',
    fallbackColor: 'from-emerald-700 via-teal-800 to-slate-900',
    badge: 'بطل معركة وادي لكة',
    gender: 'male',
    label: 'طارق بن زياد',
    emoji: '⚔️'
  },
  {
    id: 'islamic_43',
    name: 'محمد الفاتح',
    title: 'فاتح القسطنطينية ومحقق البشارة النبوية الشريفة',
    category: 'القادة والفاتحون',
    characterTag: 'نعم الأمير 🏰',
    icon: '🏰',
    fallbackColor: 'from-red-700 via-rose-800 to-amber-700',
    badge: 'فاتح القسطنطينية',
    gender: 'male',
    label: 'محمد الفاتح',
    emoji: '🏰'
  },
  {
    id: 'islamic_44',
    name: 'سيف الدين قطز',
    title: 'بطل معركة عين جالوت وهازم المغول وصاحب واإسلاماه',
    category: 'القادة والفاتحون',
    characterTag: 'واإسلاماه 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-indigo-700 via-blue-800 to-slate-950',
    badge: 'قاهر التتار',
    gender: 'male',
    label: 'سيف الدين قطز',
    emoji: '🛡️'
  },
  {
    id: 'islamic_45',
    name: 'يوسف بن تاشفين',
    title: 'أمير المسلمين وبطل معركة الزلاقة وموحد المغرب والأندلس',
    category: 'القادة والفاتحون',
    characterTag: 'أمير المسلمين 🚩',
    icon: '🚩',
    fallbackColor: 'from-emerald-800 via-teal-900 to-stone-900',
    badge: 'قائد المرابطين',
    gender: 'male',
    label: 'يوسف بن تاشفين',
    emoji: '🚩'
  },
  {
    id: 'islamic_46',
    name: 'الظاهر بيبرس',
    title: 'السلطان الشجاع وقاهر الصليبيين ومثبت أركان الدولة',
    category: 'القادة والفاتحون',
    characterTag: 'الفهد القاهر 🐆',
    icon: '🐆',
    fallbackColor: 'from-amber-700 via-orange-800 to-slate-900',
    badge: 'بطل الفتوحات',
    gender: 'male',
    label: 'الظاهر بيبرس',
    emoji: '🐆'
  },
  {
    id: 'islamic_47',
    name: 'عقبة بن نافع',
    title: 'فاتح المغرب العربي ومؤسس مدينة القيروان وجامعها',
    category: 'القادة والفاتحون',
    characterTag: 'فارس المغرب 🐎',
    icon: '🐎',
    fallbackColor: 'from-yellow-700 via-amber-800 to-emerald-950',
    badge: 'باني القيروان',
    gender: 'male',
    label: 'عقبة بن نافع',
    emoji: '🐎'
  },
  {
    id: 'islamic_48',
    name: 'موسى بن نصير',
    title: 'الفاتح العظيم لبلاد المغرب والأندلس',
    category: 'القادة والفاتحون',
    characterTag: 'فارس الفتوح ⛵',
    icon: '⛵',
    fallbackColor: 'from-cyan-700 via-blue-800 to-slate-900',
    badge: 'قائد الفتوح الكبرى',
    gender: 'male',
    label: 'موسى بن نصير',
    emoji: '⛵'
  },
  {
    id: 'islamic_49',
    name: 'قتيبة بن مسلم الباهلي',
    title: 'فاتح بلاد ما وراء النهر ومشرق العالم الإسلامي',
    category: 'القادة والفاتحون',
    characterTag: 'فاتح سمرقند 🗺️',
    icon: '🗺️',
    fallbackColor: 'from-teal-700 via-emerald-800 to-slate-900',
    badge: 'فاتح بلاد الشرق',
    gender: 'male',
    label: 'قتيبة بن مسلم',
    emoji: '🗺️'
  },
  {
    id: 'islamic_50',
    name: 'ألب أرسلان',
    title: 'الأسد الشجاع وبطل معركة ملاذكرد العظيمة',
    category: 'القادة والفاتحون',
    characterTag: 'الأسد الشجاع 🦁',
    icon: '🦁',
    fallbackColor: 'from-rose-800 via-amber-700 to-slate-950',
    badge: 'بطل ملاذكرد',
    gender: 'male',
    label: 'ألب أرسلان',
    emoji: '🦁'
  },
  {
    id: 'islamic_51',
    name: 'نور الدين محمود زنكي',
    title: 'الملك العادل موحد ديار الشام وممهد فتح القدس',
    category: 'القادة والفاتحون',
    characterTag: 'الملك العادل ⚖️',
    icon: '⚖️',
    fallbackColor: 'from-sky-700 via-blue-800 to-slate-900',
    badge: 'ناصر السنة',
    gender: 'male',
    label: 'نور الدين زنكي',
    emoji: '⚖️'
  },
  {
    id: 'islamic_52',
    name: 'عبد الرحمن الداخل',
    title: 'صقر قريش ومؤسس حضارة الأندلس الخالدة',
    category: 'القادة والفاتحون',
    characterTag: 'صقر قريش 🦅',
    icon: '🦅',
    fallbackColor: 'from-amber-600 via-orange-700 to-emerald-900',
    badge: 'صقر قريش',
    gender: 'male',
    label: 'عبد الرحمن الداخل',
    emoji: '🦅'
  },
  {
    id: 'islamic_53',
    name: 'عمرو بن العاص',
    title: 'داهية العرب وقائد فتح مصر وباني الفسطاط',
    category: 'القادة والفاتحون',
    characterTag: 'فاتح مصر 🏛️',
    icon: '🏛️',
    fallbackColor: 'from-stone-700 via-amber-800 to-slate-900',
    badge: 'باني الفسطاط',
    gender: 'male',
    label: 'عمرو بن العاص',
    emoji: '🏛️'
  },
  {
    id: 'islamic_54',
    name: 'محمد بن القاسم الثقفي',
    title: 'فاتح بلاد السند وهو فتى لم يتجاوز السابعة عشرة',
    category: 'القادة والفاتحون',
    characterTag: 'فاتح السند 🏹',
    icon: '🏹',
    fallbackColor: 'from-emerald-600 via-teal-700 to-indigo-900',
    badge: 'الفاتح الشاب',
    gender: 'male',
    label: 'محمد بن القاسم',
    emoji: '🏹'
  },
  {
    id: 'islamic_55',
    name: 'خير الدين بربروس',
    title: 'أمير البحار وقائد الأسطول الإسلامي في البحر الأبيض',
    category: 'القادة والفاتحون',
    characterTag: 'أمير البحار ⚓',
    icon: '⚓',
    fallbackColor: 'from-blue-700 via-cyan-800 to-slate-950',
    badge: 'سيد البحر المتوسط',
    gender: 'male',
    label: 'خير الدين بربروس',
    emoji: '⚓'
  },
  {
    id: 'islamic_56',
    name: 'درغوث باشا',
    title: 'فارس البحر الإسلامي وسيف الفتح العثماني البحري',
    category: 'القادة والفاتحون',
    characterTag: 'فارس البحر 🌊',
    icon: '🌊',
    fallbackColor: 'from-cyan-800 via-blue-900 to-slate-900',
    badge: 'قائد الأساطيل',
    gender: 'male',
    label: 'درغوث باشا',
    emoji: '🌊'
  },
  {
    id: 'islamic_57',
    name: 'عماد الدين زنكي',
    title: 'مؤسس الدولة الزنكية وفاتح الرها من أيدي الصليبيين',
    category: 'القادة والفاتحون',
    characterTag: 'فاتح الرها 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-slate-800 via-stone-800 to-amber-900',
    badge: 'رائد المقاومة',
    gender: 'male',
    label: 'عماد الدين زنكي',
    emoji: '🛡️'
  },
  {
    id: 'islamic_58',
    name: 'مراد الأول',
    title: 'السلطان الشهيد في معركة قوصوه وباني نهضة البلقان',
    category: 'القادة والفاتحون',
    characterTag: 'السلطان الشهيد 👑',
    icon: '👑',
    fallbackColor: 'from-red-800 via-rose-900 to-slate-900',
    badge: 'شهيد قوصوه',
    gender: 'male',
    label: 'مراد الأول',
    emoji: '👑'
  },
  {
    id: 'islamic_59',
    name: 'سليمان القانوني',
    title: 'سلطان العدل والشريعة وناشر الفتوحات في قلب أوروبا',
    category: 'القادة والفاتحون',
    characterTag: 'سلطان العدل 📜',
    icon: '📜',
    fallbackColor: 'from-amber-600 via-yellow-600 to-red-900',
    badge: 'مشرع القوانين',
    gender: 'male',
    label: 'سليمان القانوني',
    emoji: '📜'
  },
  {
    id: 'islamic_60',
    name: 'المهلب بن أبي صفرة',
    title: 'فارس الفرسان وقائد الجيوش الحكيم',
    category: 'القادة والفاتحون',
    characterTag: 'فارس الفرسان 🐎',
    icon: '🐎',
    fallbackColor: 'from-indigo-800 via-slate-800 to-stone-900',
    badge: 'الحكيم في الحروب',
    gender: 'male',
    label: 'المهلب بن أبي صفرة',
    emoji: '🐎'
  },

  // --- 4. علماء الحضارة (61-75) ---
  {
    id: 'islamic_61',
    name: 'الحسن بن الهيثم',
    title: 'مؤسس علم البصريات الحديث ومكتشف مبدأ الكاميرا',
    category: 'علماء الحضارة',
    characterTag: 'أمير البصريات 👁️',
    icon: '👁️',
    fallbackColor: 'from-sky-600 via-indigo-600 to-purple-800',
    badge: 'مؤسس علم الضوء',
    gender: 'male',
    label: 'الحسن بن الهيثم',
    emoji: '👁️'
  },
  {
    id: 'islamic_62',
    name: 'محمد بن موسى الخوارزمي',
    title: 'مؤسس علم الجبر والخوارزميات وأرقام الحساب العالمية',
    category: 'علماء الحضارة',
    characterTag: 'أبو الجبر 🔢',
    icon: '🔢',
    fallbackColor: 'from-teal-600 via-emerald-700 to-cyan-800',
    badge: 'مخترع الخوارزميات',
    gender: 'male',
    label: 'الخوارزمي',
    emoji: '🔢'
  },
  {
    id: 'islamic_63',
    name: 'ابن سينا (الشيخ الرئيس)',
    title: 'أمير الأطباء وصاحب كتاب القانون في الطب لقرون',
    category: 'علماء الحضارة',
    characterTag: 'أمير الأطباء 🩺',
    icon: '🩺',
    fallbackColor: 'from-emerald-700 via-teal-800 to-slate-900',
    badge: 'صاحب القانون في الطب',
    gender: 'male',
    label: 'ابن سينا',
    emoji: '🩺'
  },
  {
    id: 'islamic_64',
    name: 'جابر بن حيان',
    title: 'أبو الكيمياء التجريبية ومكتشف الأحماض والتقطير',
    category: 'علماء الحضارة',
    characterTag: 'أبو الكيمياء 🧪',
    icon: '🧪',
    fallbackColor: 'from-amber-600 via-orange-600 to-stone-900',
    badge: 'رائد المنهج التجريبي',
    gender: 'male',
    label: 'جابر بن حيان',
    emoji: '🧪'
  },
  {
    id: 'islamic_65',
    name: 'أبو الريحان البيروني',
    title: 'الموسوعي العبقري ومقيس نصف قطر الأرض بدقة مذهلة',
    category: 'علماء الحضارة',
    characterTag: 'عالم الفلك 🌍',
    icon: '🌍',
    fallbackColor: 'from-blue-600 via-cyan-700 to-indigo-900',
    badge: 'عبقري الجغرافيا والفلك',
    gender: 'male',
    label: 'أبو الريحان البيروني',
    emoji: '🌍'
  },
  {
    id: 'islamic_66',
    name: 'الشريف الإدريسي',
    title: 'أعظم جغرافي وصانع أول خريطة كروية دقيقة للعالم',
    category: 'علماء الحضارة',
    characterTag: 'صانع الخرائط 🗺️',
    icon: '🗺️',
    fallbackColor: 'from-teal-700 via-cyan-800 to-slate-900',
    badge: 'خارطة نزهة المشتاق',
    gender: 'male',
    label: 'الشريف الإدريسي',
    emoji: '🗺️'
  },
  {
    id: 'islamic_67',
    name: 'بديع الزمان الجزري',
    title: 'أبو علم الروبوتات والهندسة الميكانيكية وصانع الساعات',
    category: 'علماء الحضارة',
    characterTag: 'أبو الروبوتات ⚙️',
    icon: '⚙️',
    fallbackColor: 'from-orange-600 via-amber-700 to-stone-900',
    badge: 'رائد الآلات الذاتية',
    gender: 'male',
    label: 'بديع الزمان الجزري',
    emoji: '⚙️'
  },
  {
    id: 'islamic_68',
    name: 'أبو القاسم الزهراوي',
    title: 'أبو الجراحة العالمية ومخترع مئات الأدوات الطبية',
    category: 'علماء الحضارة',
    characterTag: 'أبو الجراحة ✂️',
    icon: '✂️',
    fallbackColor: 'from-emerald-600 via-teal-800 to-cyan-900',
    badge: 'مخترع أدوات الطب',
    gender: 'male',
    label: 'أبو القاسم الزهراوي',
    emoji: '✂️'
  },
  {
    id: 'islamic_69',
    name: 'يعقوب بن إسحاق الكندي',
    title: 'فيلسوف العرب ورائد علم التشفير والموسيقى الرياضية',
    category: 'علماء الحضارة',
    characterTag: 'فيلسوف العرب 🔐',
    icon: '🔐',
    fallbackColor: 'from-purple-600 via-indigo-700 to-slate-900',
    badge: 'واضع علم فك التشفير',
    gender: 'male',
    label: 'يعقوب بن إسحاق الكندي',
    emoji: '🔐'
  },
  {
    id: 'islamic_70',
    name: 'ابن النفيس الدمشقي',
    title: 'مكتشف الدورة الدموية الرئوية الصغرى في الإنسان',
    category: 'علماء الحضارة',
    characterTag: 'مكتشف الدورة الدموية 🫀',
    icon: '🫀',
    fallbackColor: 'from-rose-600 via-red-700 to-slate-900',
    badge: 'مصحح نظريات الطب',
    gender: 'male',
    label: 'ابن النفيس',
    emoji: '🫀'
  },
  {
    id: 'islamic_71',
    name: 'ثابت بن قرة',
    title: 'عالم الرياضيات والهندسة والفلك وحساب التفاضل الأولي',
    category: 'علماء الحضارة',
    characterTag: 'عالم الهندسة 📐',
    icon: '📐',
    fallbackColor: 'from-amber-600 via-yellow-700 to-stone-900',
    badge: 'المترجم والرياضي',
    gender: 'male',
    label: 'ثابت بن قرة',
    emoji: '📐'
  },
  {
    id: 'islamic_72',
    name: 'محمد بن جابر البتاني',
    title: 'أعظم علماء الفلك وحساب المثلثات ومحدد مسار الشمس',
    category: 'علماء الحضارة',
    characterTag: 'راصد الأفلاك 🔭',
    icon: '🔭',
    fallbackColor: 'from-indigo-600 via-blue-700 to-slate-950',
    badge: 'حاسب طول السنة الشمسية',
    gender: 'male',
    label: 'محمد بن جابر البتاني',
    emoji: '🔭'
  },
  {
    id: 'islamic_73',
    name: 'مريم الإسطرلابية',
    title: 'العالمة النابغة في صناعة آلات الإسطرلاب الفلكية المعقدة',
    category: 'علماء الحضارة',
    characterTag: 'صانعة الإسطرلاب 🧭',
    icon: '🧭',
    fallbackColor: 'from-purple-700 via-rose-600 to-amber-700',
    badge: 'عالمة الفلك الحلبية',
    gender: 'female',
    label: 'مريم الإسطرلابية',
    emoji: '🧭'
  },
  {
    id: 'islamic_74',
    name: 'فاطمة الفهرية',
    title: 'أم البنين ومؤسسة جامعة القرويين أقدم جامعة مستمرة بالعالم',
    category: 'علماء الحضارة',
    characterTag: 'بانية أقدم جامعة 🏛️',
    icon: '🏛️',
    fallbackColor: 'from-emerald-700 via-teal-800 to-amber-700',
    badge: 'مؤسسة جامعة القرويين',
    gender: 'female',
    label: 'فاطمة الفهرية',
    emoji: '🏛️'
  },
  {
    id: 'islamic_75',
    name: 'ابن رشد الأندلسي',
    title: 'القاضي والفيلسوف والطبيب صاحب الشروح والبداية',
    category: 'علماء الحضارة',
    characterTag: 'قاضي إشبيلية 📜',
    icon: '📜',
    fallbackColor: 'from-amber-700 via-orange-800 to-slate-900',
    badge: 'فيلسوف قرطبة',
    gender: 'male',
    label: 'ابن رشد',
    emoji: '📜'
  },

  // --- 5. أئمة وقراء (76-90) ---
  {
    id: 'islamic_76',
    name: 'الإمام محمد بن إدريس الشافعي',
    title: 'إمام المذهب الشافعي ومؤسس علم أصول الفقه والشاعر الحكيم',
    category: 'أئمة وقراء',
    characterTag: 'مؤسس أصول الفقه 📖',
    icon: '📖',
    fallbackColor: 'from-emerald-700 via-teal-700 to-cyan-900',
    badge: 'ناصر السنة',
    gender: 'male',
    label: 'الإمام الشافعي',
    emoji: '📖'
  },
  {
    id: 'islamic_77',
    name: 'الإمام مالك بن أنس',
    title: 'إمام دار الهجرة وصاحب كتاب الموطأ أول جوامع الحديث',
    category: 'أئمة وقراء',
    characterTag: 'إمام دار الهجرة 🕌',
    icon: '🕌',
    fallbackColor: 'from-amber-600 via-yellow-600 to-emerald-900',
    badge: 'صاحب الموطأ',
    gender: 'male',
    label: 'الإمام مالك',
    emoji: '🕌'
  },
  {
    id: 'islamic_78',
    name: 'الإمام أحمد بن حنبل',
    title: 'إمام أهل السنة والجماعة وصاحب المسند الشريف',
    category: 'أئمة وقراء',
    characterTag: 'إمام أهل السنة 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-teal-800 via-emerald-900 to-slate-950',
    badge: 'الصابر في المحنة',
    gender: 'male',
    label: 'الإمام أحمد بن حنبل',
    emoji: '🛡️'
  },
  {
    id: 'islamic_79',
    name: 'الإمام أبو حنيفة النعمان',
    title: 'الإمام الأعظم وفقيه الرأي والورع البالغ',
    category: 'أئمة وقراء',
    characterTag: 'الإمام الأعظم 💡',
    icon: '💡',
    fallbackColor: 'from-cyan-700 via-blue-800 to-slate-900',
    badge: 'إمام الفقهاء العراقيين',
    gender: 'male',
    label: 'الإمام أبو حنيفة',
    emoji: '💡'
  },
  {
    id: 'islamic_80',
    name: 'الإمام محمد بن إسماعيل البخاري',
    title: 'أمير المؤمنين في الحديث وصاحب أصح كتاب بعد القرآن',
    category: 'أئمة وقراء',
    characterTag: 'صاحب الصحيح 📚',
    icon: '📚',
    fallbackColor: 'from-sky-700 via-blue-800 to-indigo-950',
    badge: 'أمير الحديث',
    gender: 'male',
    label: 'الإمام البخاري',
    emoji: '📚'
  },
  {
    id: 'islamic_81',
    name: 'الإمام مسلم بن الحجاج',
    title: 'صاحب الصحيح والمحقق الفذ في أسانيد السنة النبوية',
    category: 'أئمة وقراء',
    characterTag: 'صاحب صحيح مسلم 📜',
    icon: '📜',
    fallbackColor: 'from-teal-700 via-cyan-800 to-slate-900',
    badge: 'جامع الصحيح',
    gender: 'male',
    label: 'الإمام مسلم',
    emoji: '📜'
  },
  {
    id: 'islamic_82',
    name: 'الإمام يحيى بن شرف النووي',
    title: 'محيي الدين وصاحب رياض الصالحين والأربعين النووية',
    category: 'أئمة وقراء',
    characterTag: 'صاحب رياض الصالحين 🌿',
    icon: '🌿',
    fallbackColor: 'from-emerald-600 via-green-700 to-teal-900',
    badge: 'خادم السنة المطهرة',
    gender: 'male',
    label: 'الإمام النووي',
    emoji: '🌿'
  },
  {
    id: 'islamic_83',
    name: 'الإمام عاصم بن أبي النجود',
    title: 'إمام القراء الكوفيين صاحب الرواية الشهيرة (حفص عن عاصم)',
    category: 'أئمة وقراء',
    characterTag: 'شيخ القراء الكوفيين 🎙️',
    icon: '🎙️',
    fallbackColor: 'from-amber-600 via-orange-700 to-stone-900',
    badge: 'رواية حفص عن عاصم',
    gender: 'male',
    label: 'الإمام عاصم',
    emoji: '🎙️'
  },
  {
    id: 'islamic_84',
    name: 'الإمام نافع المدني',
    title: 'أحد القراء السبعة الكبار وشيخ الإقراء بمسجد النبي ﷺ',
    category: 'أئمة وقراء',
    characterTag: 'إمام قراء المدينة 🌙',
    icon: '🌙',
    fallbackColor: 'from-teal-600 via-emerald-800 to-slate-900',
    badge: 'قارئ المدينة المنورة',
    gender: 'male',
    label: 'الإمام نافع',
    emoji: '🌙'
  },
  {
    id: 'islamic_85',
    name: 'سيبويه (عمرو بن عثمان)',
    title: 'إمام النحاة وحجة لغة القرآن وصاحب (الكتاب)',
    category: 'أئمة وقراء',
    characterTag: 'إمام النحاة 🖋️',
    icon: '🖋️',
    fallbackColor: 'from-indigo-700 via-purple-800 to-slate-900',
    badge: 'حجة لغة الضاد',
    gender: 'male',
    label: 'سيبويه',
    emoji: '🖋️'
  },
  {
    id: 'islamic_86',
    name: 'عبد الرحمن بن خلدون',
    title: 'مؤسس علم الاجتماع وفلسفة التاريخ وصاحب المقدمة',
    category: 'أئمة وقراء',
    characterTag: 'صاحب المقدمة 📜',
    icon: '📜',
    fallbackColor: 'from-amber-700 via-stone-800 to-slate-950',
    badge: 'مؤسس علم العمران',
    gender: 'male',
    label: 'ابن خلدون',
    emoji: '📜'
  },
  {
    id: 'islamic_87',
    name: 'الحافظ ابن كثير',
    title: 'المفسر والمؤرخ الكبير صاحب تفسير القرآن والبداية والنهاية',
    category: 'أئمة وقراء',
    characterTag: 'مفسر القرآن 📖',
    icon: '📖',
    fallbackColor: 'from-blue-700 via-indigo-800 to-slate-900',
    badge: 'عمدة المفسرين',
    gender: 'male',
    label: 'ابن كثير',
    emoji: '📖'
  },
  {
    id: 'islamic_88',
    name: 'الإمام ابن تيمية',
    title: 'شيخ الإسلام والمدافع عن عقيدة السلف ومجدد زمانه',
    category: 'أئمة وقراء',
    characterTag: 'شيخ الإسلام ⚔️',
    icon: '⚔️',
    fallbackColor: 'from-slate-700 via-stone-800 to-amber-950',
    badge: 'فارس الحجة والبيان',
    gender: 'male',
    label: 'الإمام ابن تيمية',
    emoji: '⚔️'
  },
  {
    id: 'islamic_89',
    name: 'الإمام ابن قيم الجوزية',
    title: 'طبيب القلوب وصاحب زاد المعاد ومدارج السالكين',
    category: 'أئمة وقراء',
    characterTag: 'طبيب القلوب 💖',
    icon: '💖',
    fallbackColor: 'from-emerald-700 via-teal-800 to-slate-900',
    badge: 'صاحب مدارج السالكين',
    gender: 'male',
    label: 'ابن القيم',
    emoji: '💖'
  },
  {
    id: 'islamic_90',
    name: 'الإمام أبو حامد الغزالي',
    title: 'حجة الإسلام وصاحب كتاب إحياء علوم الدين',
    category: 'أئمة وقراء',
    characterTag: 'حجة الإسلام 🕯️',
    icon: '🕯️',
    fallbackColor: 'from-indigo-700 via-cyan-800 to-slate-900',
    badge: 'إحياء علوم الدين',
    gender: 'male',
    label: 'الإمام الغزالي',
    emoji: '🕯️'
  },

  // --- 6. أشبال وزهرات القرآن (91-100) ---
  {
    id: 'islamic_91',
    name: 'شبل المحراب الحافظ',
    title: 'طالب القرآن المتقن المرتل بآيات الذكر الحكيم',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'حافظ القرآن 📖',
    icon: '📖',
    fallbackColor: 'from-emerald-500 via-teal-600 to-cyan-700',
    badge: 'المرتل المتقن',
    gender: 'male',
    label: 'شبل المحراب',
    emoji: '📖'
  },
  {
    id: 'islamic_92',
    name: 'فارس أكاديمية سبيل',
    title: 'فارس الهمة والمنافسة الشريفة في حلقات العلم',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'فارس سبيل 🛡️',
    icon: '🛡️',
    fallbackColor: 'from-sky-500 via-blue-600 to-indigo-700',
    badge: 'بطل الانضباط',
    gender: 'male',
    label: 'فارس سبيل',
    emoji: '🛡️'
  },
  {
    id: 'islamic_93',
    name: 'شبل الهمة والسباق',
    title: 'المتسابق الأول في حصد النقاط واعتلاء صدارة الحلقات',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'الأول بالصدارة 🏆',
    icon: '🏆',
    fallbackColor: 'from-amber-500 via-yellow-500 to-orange-600',
    badge: 'فارس الصدارة',
    gender: 'male',
    label: 'شبل الهمة',
    emoji: '🏆'
  },
  {
    id: 'islamic_94',
    name: 'زهرة الإيمان والعفاف',
    title: 'طالبة القرآن المتألقة بحسن الترتيل والخلق الرفيع',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'زهرة الإيمان 🌸',
    icon: '🌸',
    fallbackColor: 'from-rose-500 via-pink-500 to-purple-600',
    badge: 'حسن الترتيل',
    gender: 'female',
    label: 'زهرة الإيمان',
    emoji: '🌸'
  },
  {
    id: 'islamic_95',
    name: 'لؤلؤة الوقار والهدى',
    title: 'الحافظة المجدّة المتوجة بتاج الكرامة والسكينة',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'لؤلؤة الوقار 💎',
    icon: '💎',
    fallbackColor: 'from-teal-500 via-emerald-600 to-cyan-700',
    badge: 'تاج الكرامة',
    gender: 'female',
    label: 'لؤلؤة الوقار',
    emoji: '💎'
  },
  {
    id: 'islamic_96',
    name: 'حامل المسك القرآني',
    title: 'قدوة أقرانه في المحبة والتعاون وأدب مجالس القرآن',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'حامل المسك 🌺',
    icon: '🌺',
    fallbackColor: 'from-purple-500 via-indigo-600 to-blue-700',
    badge: 'قدوة المجلس',
    gender: 'male',
    label: 'حامل المسك',
    emoji: '🌺'
  },
  {
    id: 'islamic_97',
    name: 'بطل الفجر والمحراب',
    title: 'المبكر إلى الصفوف الأولى والتلاوة بصفاء قلب',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'بطل الفجر 🌅',
    icon: '🌅',
    fallbackColor: 'from-orange-500 via-amber-500 to-yellow-600',
    badge: 'نور الفجر',
    gender: 'male',
    label: 'بطل الفجر',
    emoji: '🌅'
  },
  {
    id: 'islamic_98',
    name: 'سفير الضياء والحكمة',
    title: 'الطالب المتفوق علمياً وخلقياً والناشر للخير',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'سفير الضياء 🌟',
    icon: '🌟',
    fallbackColor: 'from-cyan-500 via-teal-600 to-emerald-700',
    badge: 'سفير الحكمة',
    gender: 'male',
    label: 'سفير الضياء',
    emoji: '🌟'
  },
  {
    id: 'islamic_99',
    name: 'نجم المتون والتجويد',
    title: 'الحافظ المتقن لمنظومات التجويد وأحكام الأداء السليم',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'نجم التجويد ⭐',
    icon: '⭐',
    fallbackColor: 'from-violet-500 via-purple-600 to-indigo-700',
    badge: 'متقن الأداء',
    gender: 'male',
    label: 'نجم المتون',
    emoji: '⭐'
  },
  {
    id: 'islamic_100',
    name: 'خاتم القرآن الذهبي',
    title: 'المتمم لكتاب الله تعالى كاملاً غضاً طرياً بفضل الله',
    category: 'أشبال وزهرات القرآن',
    characterTag: 'خاتم القرآن 👑',
    icon: '👑',
    fallbackColor: 'from-amber-400 via-yellow-500 to-amber-600',
    badge: 'خاتم كتاب الله',
    gender: 'any',
    label: 'خاتم القرآن',
    emoji: '👑'
  }
];

// Helper to look up any avatar with seamless fallback
export const getIslamicAvatar = (id?: string): IslamicAvatarDef => {
  if (!id) return ISLAMIC_AVATARS[0];
  const found = ISLAMIC_AVATARS.find((a) => a.id === id);
  if (found) return found;

  // Map legacy IDs gracefully (e.g. naruto_1, avatar_1, etc.)
  if (id.startsWith('naruto') || id === 'avatar_1') return ISLAMIC_AVATARS[4]; // خالد بن الوليد (سيف الله)
  if (id.startsWith('eren') || id === 'avatar_7') return ISLAMIC_AVATARS[41]; // صلاح الدين
  if (id.startsWith('levi') || id === 'avatar_3') return ISLAMIC_AVATARS[40]; // طارق بن زياد
  if (id.startsWith('luffy') || id === 'avatar_5') return ISLAMIC_AVATARS[91]; // فارس سبيل
  if (id.startsWith('goku') || id === 'avatar_6') return ISLAMIC_AVATARS[90]; // شبل المحراب
  if (id.startsWith('nezuko') || id === 'avatar_2') return ISLAMIC_AVATARS[93]; // زهرة الإيمان
  if (id.startsWith('mikasa') || id === 'avatar_4') return ISLAMIC_AVATARS[28]; // أسماء بنت أبي بكر

  return ISLAMIC_AVATARS[0];
};
